#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Sat May 02 23:20:43 GMT-03:00 2026
alwaysLogTamperWarnings=false
